#application default configuration
CONFIG_CPP=y
CONFIG_STD_CPP17=y
# Include TFLM based on CMSIS NN optimization and ETHOSU acceleration
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_TENSORFLOW_LITE_MICRO_CMSIS_NN_KERNELS=y
# Enable Ethos-U support
CONFIG_ETHOS_U=y
# Disable Ethos-U D-Cache flush/invalidate operations 
CONFIG_ETHOS_U_DCACHE=n
# Set main stack size to 16 KB
CONFIG_MAIN_STACK_SIZE=16384
# Set heap memory pool size to 64 KB
CONFIG_HEAP_MEM_POOL_SIZE=65536
# Enable Floating Point Unit (FPU) support
CONFIG_FPU=y
# Enable logging subsystem
CONFIG_LOG=y
# Enable floating point support in printf
CONFIG_REQUIRES_FLOAT_PRINTF=y
# Set system tick frequency to 1000 Hz
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
# Enable compiler optimizations for vectorization
CONFIG_COMPILER_OPT="-ftree-vectorize"
# Enable I/D cache
CONFIG_CACHE_MANAGEMENT=y

# Object detection application specific configurations
# Enable application profiling
CONFIG_APP_OD_PROFILE_ENABLED=n
# Load model from SD Card to HyperRAM
CONFIG_APP_OD_MODEL_FROM_SD=n
# Use HyperRAM for arena/model space
CONFIG_APP_OD_USING_HYPERRAM=n
# Show result image over UVC
CONFIG_APP_OD_UVC_SHOW_IMAGE=y
# Show result image over LCD
CONFIG_APP_OD_LCD_SHOW_IMAGE=n
